### ISSUE TITLE
关于实验一文档的一些改进建议

### ISSUE THREAD

**Issue by zzh1996** [OSH-2018/OSH-2018.github.io#1]
1. 实验一的参考代码有以下问题：当标准输入不以换行符结束时，最后一行不会写到 output.txt 中
2. 建议「虚拟化软件」列表增加（非商用）免费的 [vmware player](https://www.vmware.com/products/workstation-player.html)
3. 桌面环境中的 XFACE 是拼写错误？应该是 XFCE 吧

**Comment by lizitian** [comment]
fixed
